default amountToUnits decimals to 18, FRE consumerMarketSwapFee witho…
oceanprotocol/ocean.js pull request #1374
Opened 2022-03-28 01:42 UTC by soonhuat

…ut basetoken

Fixes # .

Changes proposed in this PR:

- FRE calcBaseInGivenOutDT method with consumeMarketSwapFee non-token specific, since is % of defined price
- amountToUnits with default token decimals to 0

2022-03-28 09:09 UTC, mihaisc commented
Don't change `amountToUnits` function, just use Web3.utils.toWei

2022-03-28 09:49 UTC, kremalicious commented on src/utils/ContractUtils.ts
> +    let decimals = token ? await tokenContract.methods.decimals().call() : '0'
what weird logic combined with next 3 lines which should be all removed. If `decimals` is set here to `'0'` as part of `else` then no need to check for it again in next lines to set it to something else again. So for `else`, `decimals` here should be just `18` and then no need for the next 3 lines. And then it's a `const` and no `let`

2022-03-28 09:51 UTC, kremalicious commented
> amountToUnits with default token decimals to 0

the code does not reflect this as `decimals` is immediately set to `18` as soon as `decimals` is `'0'`. Commented on respective code line above.

And then what Mihai said, I don't have any context on this PR as no issue to be found describing what it tried to solve so no `amountToUnits` usage as it looks like

2022-03-28 10:53 UTC, mihaisc commented
Yes it's a simple solution somthing like 
```
.calcBaseInGivenOutDT(
        exchangeId,
        await this.amountToUnits(fixedRateExchange.datatoken, datatokenAmount),
        Web3.utils.toWei(consumeMarketFee)
      )
```

2022-03-28 14:40 UTC, soonhuat commented
@mihaisc ya, that's the right way to go, earlier got blinded by the existing conversion method

2022-03-28 14:46 UTC, mihaisc approved these changes

2022-03-29 14:42 UTC, kremalicious requested changes
`test_integration` needs to succeed, `test_unit` is fine failing if only 1 specific test fails at the moment (Pool unit test - Test a pool with DAI (18 Decimals) - #swapExactAmountIn - should swap)

2022-03-29 14:43 UTC, mihaisc commented
Test integration fails because of compute timeoute issue

2022-03-29 14:54 UTC, merged